### ISSUE TITLE
Thunar

### ISSUE THREAD

**Issue by inari-codes** [Ashwatthaamaa/Neuwaita#16] opened 2022-05-23 04:51 UTC
It's the file manager for Xfce desktop environment 

Icon name: `org.xfce.thunar`

Original icon:
![107598377-fe92cf00-6c36-11eb-8a41-cadb693cfa05](https://user-images.githubusercontent.com/85934291/169745433-b0942bba-6007-4a22-a1ba-35b47547c0de.png)

**Comment by Ashwatthaamaa** [comment] 2022-05-23 11:38
Duplicate of #9

**Closed as completed by Ashwatthaamaa** 2022-05-23 11:38 UTC
