### ISSUE TITLE
Keepassxc

### ISSUE THREAD

**Issue by setPrimse** [Ashwatthaamaa/Neuwaita#11] opened 2022-05-22 22:41 UTC
`keepassxc.svg` and `keepassxc-unlocked.svg`: Community repo, i believe.
And `org.keepassxc.KeePassXC` for flatpak.

**Comment by Ashwatthaamaa** [comment] 2022-05-23 02:37
This icon request makes me so happy !! thanks :)

Duplicate of #9

**Closed as completed by Ashwatthaamaa** 2022-05-23 02:37 UTC
