### ISSUE TITLE
Create an emacs and thunderbird icon

### ISSUE THREAD

**Issue by pacberries** [Ashwatthaamaa/Neuwaita#1] opened 2022-05-21 11:50 UTC
Title says it all

**Comment by Ashwatthaamaa** [comment] 2022-05-21 12:20
@pacbru1260 do you know the name of the icons? you can find out the name as mentioned in the readme. It would be helpful if you can :)

**Comment by pacberries** [comment] 2022-05-21 12:49
> @pacbru1260 do you know the name of the icons? you can find out the name as mentioned in the readme. It would be helpful if you can :)

The emacs one is **emacs** and thunderbird's is **thunderbird**

**Comment by Ashwatthaamaa** [comment] 2022-05-21 12:58
@pacbru1260 thanks ... I have pushed the emacs icon !! I also made an emacs icon for flatpak too. 

lol any ideas for thunderbird icon? its good as it is but would love to make something new so if you have suggestions then let me know!! cheers !!

**Comment by Ashwatthaamaa** [comment] 2022-05-22 05:12
Duplicate of #9

**Closed as completed by Ashwatthaamaa** 2022-05-22 05:12 UTC
